### ISSUE TITLE
Building 'gssapi.raw.ext_cred_store' extension on SLES 15.1 stops with "gssapi/raw/ext_cred_store.c:1333:8: error: unknown type name ‘gss_key_value_set_desc’"

### ISSUE THREAD

**Issue by RolandFelnhofer** [pythongssapi/python-gssapi#212] opened 2020-06-30 10:19 UTC
### What went wrong?
When building python-gssapi ist stops with "gssapi/raw/ext_cred_store.c:1333:8: error: unknown type name ‘gss_key_value_set_desc’"

### How do we reproduce?
```
$ cd /usr/src/gssapi-1.6.5
$ python3 -mvenv buildenv
$ source buildenv/bin/activate
$ mkdir wheels
$ export PATH=$PATH:$(dirname $(locate -r "krb5-config$"))
$ pip install -U pip wheel setuptools
$ pip wheel -w wheels/ pip wheel setuptools
$ pip wheel -w wheels/ pip wheel gssapi
```

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)
python-gssapi: 1.6.5
OS: SUSE Linux Enterprise Server 15 SP1
```
$ krb5-config --all
Version:     Kerberos 5 release 1.16.3
Vendor:      Massachusetts Institute of Technology
Prefix:      /usr/lib/mit
Exec_prefix: /usr/lib/mit
```

### Reason
I found out that in setup.py, between line 103 and 114, tries to detect the location of 'gssapi_ext.h', by executing 'krb5-config gssapi --prefix' and adding 'include/gssapi/gssapi_ext.h' to that prefix. 

On SLES 15.1 (and other SUSE distributions I assume) the location of the include files for gssapi are within the regular include path ('/usr/include'). So the full path for the header file is '/usr/include/gssapi/gssapi_ext.h' and not '/usr/lib/mit/include/gssapi/gssapi_ext.h' as expected by 'setup.py'

Can you please add a check if 'gssapi_ext.h' exists within the regular include structure?

### Workaround
As a temporary workaround I used:
```
$ pip wheel --global-option=build_ext --global-option="-DHAS_GSSAPI_EXT_H" -w wheels/ gssapi
```
to force to include the header file 'gssapi_ext.h'

**Comment by frozencemetery** [comment] 2020-06-30 19:38
I'm pretty sure this is a bug in SUSE.  This should match to the autoconf prefix from building krb5 - see https://github.com/krb5/krb5/blob/master/src/build-tools/krb5-config.in#L30

For completeness, here are some other distros and their values:

Debian testing:
```
rharwood@seton:~$ krb5-config --all
Version:     Kerberos 5 release 1.17
Vendor:      Massachusetts Institute of Technology
Prefix:      /usr
Exec_prefix: /usr
```

Fedora rawhide:
```
[vagrant@localhost ~]$ krb5-config --all
Version:     Kerberos 5 release 1.18.2
Vendor:      Massachusetts Institute of Technology
Prefix:      /usr
Exec_prefix: /usr
```

el8:
```
[vagrant@rhel8 ~]$ krb5-config --all
Version:     Kerberos 5 release 1.17
Vendor:      Massachusetts Institute of Technology
Prefix:      /usr
Exec_prefix: /usr
```

el7:
```
[vagrant@rhel7 ~]$ krb5-config --all
Version:     Kerberos 5 release 1.15.1
Vendor:      Massachusetts Institute of Technology
Prefix:      /usr
Exec_prefix: /usr
[vagrant@rhel7 ~]$ 
```

**Comment by RolandFelnhofer** [comment] 2020-07-01 10:38
I agree with you that krb5-config should reflect the actual location of the individual directories (`./bin`, `./sbin`, `./lib`, `./lib64`, `./share`, `./include`) 
`krb5-config.in` honers, beside of `prefix` and `exec_prefix` also `includedir` and `libdir` where `krb5-config` (script) only knows of `--prefix` and `--exec-prefix`. I think the most elegant way would be, if this additional locations could also be queried/reported by `krb5-config`.

For the time being  krb5-config --all should report the following on SUSE:
````
$ krb5-config --all
Version:     Kerberos 5 release 1.16.3
Vendor:      Massachusetts Institute of Technology
Prefix:      /usr
Exec_prefix: /usr/lib/mit
````
as `./bin`, `./sbin` and `./share` (which is actually an empty directory) are located beneath `/usr/lib/mit`.

Ideally the output of `krb5-config` should look the following way in future:
````
$ krb5-config --all
Version:     Kerberos 5 release 1.16.3
Vendor:      Massachusetts Institute of Technology
Prefix:      /usr
Exec_prefix: /usr/lib/mit
Includedir: /usr/include
Libdir: /usr/lib
````
Looking into the `krb5-config` script shows the following values:
`...`
`prefix=/usr/lib/mit`
`exec_prefix=${prefix}`
`includedir=/usr/include`
`libdir=/usr/lib`
`...`

I'll will try to open a case at SUSE to get a solution from there side as well.

My main motivation of opening this case here was, to have a prominent place, where I can document the workaround, for all using SUSE as their Linux distribution.

**Comment by greghudson** [comment] 2020-07-01 14:28
I think we can assign a bit of blame everywhere.  It sounds like python-gssapi is at fault for:

* Divining includedir from prefix.
* Testing for whether gssapi_ext.h can be included by determining its exact location.
* Testing for gssapi_ext.h and not including it if it doesn't seem to be present, but then failing to build.

SLES may not be strictly at fault from a Gnu software configuration perspective, but they are definitely doing their own weird thing with the krb5 build options, and fallout like this is a predictable consequence.

MIT krb5 is perhaps at fault for not having a krb5-config --includedir option.  It has --cflags, but scraping that is questionable (and not trivial, because it gives no output if includedir is /usr/include).

python-gssapi could use "pkg-config --variable=includedir krb5-gssapi" at the cost of a pkg-config dependency.  I don't know if it has better options for testing for the presence of the header.  An autoconf-generated configure script would invoke the compiler to see if "#include <gssapi_ext.h" throws an error, but there's a lot of autoconf infrastructure behind that, and as far as I know Python setup scripts don't have the same facilities.

**Comment by frozencemetery** [comment] 2020-07-01 19:20
I no longer remember why we do it this way, but my concerns with the pkg-config approach would be adding the dependency - I'm not sure how viable that is on non-Linux.

We also need to verify whether the file exists because Heimdal doesn't have it, and our includes need to be modified appropriately.  (I believe this is how the build failure occurs: we hit the Heimdal support paths on MIT.)

We might be able to do something in setup.py, but I'm not immediately seeing how that's better - that would mean we have to go duplicate all the autotools/cython logic for finding and wrangling the C compiler, and I'd really rather not.

If MIT wants to add a includedir option, that's fine, but doesn't help Heimdal, and more importantly doesn't help older platforms.

In light of all that: I'd like to hear what SUSE has to say, but it seems like the best way forward will be to add SUSE-specific changes to setup.py.

**Comment by RolandFelnhofer** [comment] 2020-07-02 07:18
I've opened a SUSE case as well. The case number is: 00203388 (https://scc.suse.com/support/cases/00203388). As it is a SLES case, I don't know if it is publicly available but I can post here regular updates.

Currently I'm discussing if a support bundle is required to continue working on my case.

**Comment by frozencemetery** [comment] 2020-07-02 14:27
Thanks.  It looks private, so please keep us posted how it turns out or if it stalls.

**Comment by RolandFelnhofer** [comment] 2020-07-13 15:02
Update from SUSE:

> From: SUSE Technical Support <techsupport@suse.com> 
> Sent: Montag, 13. Juli 2020 14:57
> To: FELNHOFER Roland <roland.felnhofer@xxxxxxxx.xxx>
> Subject: RE: Building python-gssapi 'gssapi.raw.ext_cred_store' extension on SLES 15.1 stops with "gssapi/raw/ext_cred_store.c:1333:8: error: unknown type name ‘gss_key_value_set_desc’" [ ref:_00D1igLOd._5001iPzvBm:ref ]
> 
> Dear Roland,
> 
> my name is Aziz, I'm a support engineer from SUSE assigned to assist you in
> this case.
> 
> With regards to the python-gssapi build issues, I've reviewed the problem
> description, issues as far as I understand is in the krb5-config utility, I opened a
> bug report with our engineering team.
> 
> I'll let know as soon as they will provided us their feedback.
> 
> Thank you
> 
> Kind regards
> Aziz Rozyev
> Technical support engineer
> ---
> SUSE Software Solutions Germany GmbH
> Maxfeldstr.5, 90409 Nuremberg, Germany
>

**Comment by RolandFelnhofer** [comment] 2020-08-27 08:35
SUSE provided a Program Temporary Fix (PTF) for my case.
The bug number of my case is: 1174079.

As soon as the fix becomes part of the regular maintenance fixes/patches this bug number should be mentioned in the release note.

After applying the PTF it shows:

```
$ krb5-config --all
Version:     Kerberos 5 release 1.16.3
Vendor:      Massachusetts Institute of Technology
Prefix:      /usr
Exec_prefix: /usr/lib/mit
```

How to check if the patch is part of the installed patches:
```
$ rpm -qa krb5* | xargs rpm -qi --changelog | grep 1174079
```
The output should look similar to:
```

**Comment by arozyev** [comment] 2020-08-27 12:03
Dear project owners, I'm that engineer worked on the case from SUSE side, could you please be so kind and remove any references to company and to me. It's fine to keep technically relevant text, but I'd prefer not seeing my name and links to the internal suse resource on public domain (perhaps including this comment). Thank you very much in advance.

**Comment by frozencemetery** [comment] 2020-08-27 14:20
Hi, without specific guidance on what you want removed, we've used our best judgement.  It's not our intent to call out specific people, or blame anyone for problems.

- References to SUSE will stay because we're trying to get a change in SLES.

- The fact that a case has or has not been opened is Roland's choice to share, since they filed it (unless you've previously agreed on something else I'm not privy to).

- You should be able to delete your own comment if you desire to do so.  If that's not correct, post again and I'll take care of it.

If there are specific additional things you would like changed, please let us know; otherwise I'm going to consider the matter resolved.

**Comment by arozyev** [comment] 2020-08-27 20:51
> Hi, without specific guidance on what you want removed, we've used our best judgement. It's not our intent to call out specific people, or blame anyone for problems.
> 
> * References to SUSE will stay because we're trying to get a change in SLES.
> * The fact that a case has or has not been opened is Roland's choice to share, since they filed it (unless you've previously agreed on something else I'm not privy to).
> * You should be able to delete your own comment if you desire to do so.  If that's not correct, post again and I'll take care of it.
> 
> If there are specific additional things you would like changed, please let us know; otherwise I'm going to consider the matter resolved.

looks good now, thanks for your quick action.

**Comment by frozencemetery** [comment] 2021-08-04 22:44
Been a year, so I'm going to close this one out, but we can reopen if further discussion is warranted.

**Closed by frozencemetery** 2021-08-04 22:44 UTC

**Comment by nmz787** [comment] 2021-10-13 03:37
There's not an actual workaround here for SLES users seemingly facing the same issue. I've just created a SUSE account with my job email, but I can't access the case number (which the automated system says is possibly due to my administrator disabling access to support... so I guess I'll try sending this URL to my IT dept).

How do I quickly change things to match the earlier comment of the desired output being:
```
$ krb5-config --all
Version:     Kerberos 5 release 1.16.3
Vendor:      Massachusetts Institute of Technology
Prefix:      /usr
Exec_prefix: /usr/lib/mit
Includedir: /usr/include
Libdir: /usr/lib
```

or otherwise move past this issue?

**Comment by jborean93** [comment] 2021-10-13 05:07
The trouble is there are cases where the file may not exist, Heimdal is a common distribution which does not have this header. We also cannot just use a whitelist set of paths in cases where a GSSAPI provider was installed to a custom path. A very uncommon cse where just searching known paths is when you have both Heimdal and MIT installed but to have a separate GSSAPI install for either.

**Comment by grepwood** [comment] 2022-10-06 11:28
This is reproducible at work, where we use NixOS and it's blocking our upgrade of frameworks in the project.

**Comment by grepwood** [comment] 2022-10-10 18:34
Fixed! You need to figure out what this patch does for NixOS and apply for your distro:
https://github.com/NixOS/nixpkgs/blob/8ff7b290e6dd47d7ed24c6d156ba60fc3c83f100/pkgs/development/python-modules/gssapi/default.nix#L31-L34

**Comment by nmz787-intel** [comment] 2023-08-30 00:07
> ```diff
> gssapi_ext_h = os.path.join('/usr', 'include/gssapi/gssapi_ext.h')
> ```

this is still the workaround I just had to do... almost 2 years later:

`git clone https://github.com/pythongssapi/python-gssapi.git`
...apply patch to setup.py...
`pip install -e .`
...move on with my life...
