### ISSUE TITLE
Duplicate docs updates fail

### ISSUE THREAD

**Issue by frozencemetery** [pythongssapi/python-gssapi#140] opened 2018-01-03 17:42 UTC
### What went wrong?

While trying to run CI in (weekly) cron, I noticed that the "deploy latest docs" does not work there, presumably because it's trying to push a hash which has already been pushed.

### How do we reproduce?

A failing build is [here](https://travis-ci.org/pythongssapi/python-gssapi/).

**Comment by DirectXMan12** [comment] 2018-01-03 18:12
duplicate of #136

**Closed by DirectXMan12** 2018-01-03 18:12 UTC
Labels: build
