### ISSUE TITLE
NotImplementedError: Your GSSAPI implementation does not have support for manipulating credential stores

### ISSUE THREAD

**Issue by krizex** [pythongssapi/python-gssapi#216] opened 2020-07-08 01:59 UTC
### What went wrong?
We got the following traceback when using v1.6.7
**Note**
But when we using v1.6.5, we never met this issue before.
```
...
File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 587, in bind    response = self.do_sasl_bind(controls)  
File "/usr/local/lib/python3.8/dist-packages/ldap3/core/connection.py", line 1293, in do_sasl_bind    result = sasl_gssapi(self, controls)  
File "/opt/ad-service/adagent/patches/ldap3/kerberos.py", line 114, in sasl_gssapi    creds = gssapi.Credentials(name=gssapi.Name(connection.user), usage='initiate', store=connection.cred_store) if connection.user else None  
File "/usr/local/lib/python3.8/dist-packages/gssapi/creds.py", line 63, in __new__    res = cls.acquire(name, lifetime, mechs, usage,  
File "/usr/local/lib/python3.8/dist-packages/gssapi/creds.py", line 140, in acquire    raise NotImplementedError("Your GSSAPI implementation does "NotImplementedError: Your GSSAPI implementation does not have support for manipulating credential stores
```

### How do we reproduce?
It should be easy to reproduce in Ubuntu 20.04 by installing the packages I listed below.
*(Remember to use fenced code blocks and consider placing in a gist if large)*

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)

*(Please include MIT/Heimdal/etc. and how you installed python-gssapi)*
Install python-gssapi by `pip3 install gssapi`
OS: Ubuntu 20.04
KRB5: 
```
root@8040afa9c7fa:/opt/ad-service# apt list --installed | grep krb
libgssapi-krb5-2/focal,now 1.17-6ubuntu4 amd64 [installed,automatic]
libkrb5-26-heimdal/focal,now 7.7.0+dfsg-1ubuntu1 amd64 [installed,automatic]
libkrb5-3/focal,now 1.17-6ubuntu4 amd64 [installed,automatic]
libkrb5support0/focal,now 1.17-6ubuntu4 amd64 [installed,automatic]
```
Python: 3.8.2

**Comment by frozencemetery** [comment] 2020-07-08 02:09
Duplicate of #215; should be resolved now that 1.6.9 is out.

**Closed by frozencemetery** 2020-07-08 02:09 UTC
