### ISSUE TITLE
Support GSS_C_DELEG_POLICY_FLAG

### ISSUE THREAD

**Issue by jborean93** [pythongssapi/python-gssapi#217] opened 2020-07-09 03:04 UTC
### What went wrong?
The `GSS_C_DELEG_POLICY_FLAG` is not defined anywhere in this library. Unfortunately a user cannot just manually do a bitwise or with `gssapi.RequirementFlag` due to Python enum failing saying it isn't a valid value.

I'm not sure whether python-gssapi wants to always validate the flags that are needed and this one just needs to be added to the enum, or whether it should allow any flags to be passed in regardless of whether it's under `RequirementFlag`.

### How do we reproduce?

```python
import gssapi

  # Nothing is in here, as expected because it isn't defined anywhere in the code
print(dir(gssapi.RequirementFlag))

flags = gssapi.RequirementFlag.delegate_to_peer | 0x00080000
kerberos = gssapi.OID.from_int_seq('1.2.840.113554.1.2.2')
spn = gssapi.Name('host@dc.domain.com', name_type=gssapi.NameType.hostbased_service)

# The .step() call will fail because the flags try to be casted to RequirementFlag which won't work
gssapi.SecurityContext(usage='initiate', flags=flags, mech=kerberos, name=spn).step()
```

The output of the above is

```text
**['__class__', '__doc__', '__members__', '__module__', 'anonymity', 'confidentiality', 'dce_style', 'delegate_to_peer', 'extended_error', 'identify', 'integrity', 'mutual_authentication', 'out_of_sequence_detection', 'protection_ready', 'replay_detection', 'transferable']
ValueError: 524288 is not a valid RequirementFlag

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "abc.py", line 10, in <module>
    gssapi.SecurityContext(usage='initiate', flags=flags, mech=kerberos, name=spn).step()
  File "<decorator-gen-15>", line 2, in step
  File "/home/jborean/venvs/ansible-py38/lib/python3.8/site-packages/gssapi/_utils.py", line 169, in check_last_err
    return func(self, *args, **kwargs)
  File "<decorator-gen-5>", line 2, in step
  File "/home/jborean/venvs/ansible-py38/lib/python3.8/site-packages/gssapi/_utils.py", line 129, in catch_and_return_token
    return func(self, *args, **kwargs)
  File "/home/jborean/venvs/ansible-py38/lib/python3.8/site-packages/gssapi/sec_contexts.py", line 521, in step
    return self._initiator_step(token=token)
  File "/home/jborean/venvs/ansible-py38/lib/python3.8/site-packages/gssapi/sec_contexts.py", line 537, in _initiator_step
    res = rsec_contexts.init_sec_context(self._target_name, self._creds,
  File "gssapi/raw/sec_contexts.pyx", line 179, in gssapi.raw.sec_contexts.init_sec_context
  File "gssapi/raw/types.pyx", line 234, in gssapi.raw.types.IntEnumFlagSet.__init__
  File "gssapi/raw/types.pyx", line 136, in gssapi.raw.types.GenericFlagSet.__init__
  File "gssapi/raw/types.pyx", line 238, in __iter__
  File "/home/jborean/venvs/ansible-py38/lib/python3.8/enum.py", line 304, in __call__
    return cls.__new__(cls, value)
  File "/home/jborean/venvs/ansible-py38/lib/python3.8/enum.py", line 595, in __new__
    raise exc
  File "/home/jborean/venvs/ansible-py38/lib/python3.8/enum.py", line 579, in __new__
    result = cls._missing_(value)
  File "/home/jborean/venvs/ansible-py38/lib/python3.8/enum.py", line 608, in _missing_
    raise ValueError("%r is not a valid %s" % (value, cls.__name__))
ValueError: 524288 is not a valid RequirementFlag
```

### Component versions (python-gssapi, Kerberos, OS / distro, etc.)

python-gssapi: 1.6.7 (through pip)
MIT krb5: Kerberos 5 release 1.18.2

**Comment by frozencemetery** [comment] 2020-07-09 17:59
> I'm not sure whether python-gssapi wants to always validate the flags that are needed and this one just needs to be added to the enum, or whether it should allow any flags to be passed in regardless of whether it's under RequirementFlag.

Our intent is that only flags we understand would be supported.  This choice could be revisited of course, but I think we're in agreement that it's better to add support to the library for the flag rather than littering other codebases with opaque constants :)

It's less dire than it sounds, too.  python-gssapi's extension support can add flags; see for instance [the handling of DCE](https://github.com/pythongssapi/python-gssapi/blob/master/gssapi/raw/_enum_extensions/ext_dce.pyx).

**Comment by frozencemetery** [comment] 2020-07-09 18:02
In any case, duplicate of #132.

**Closed by frozencemetery** 2020-07-09 18:02 UTC
Labels: enhancement

**Comment by jborean93** [comment] 2020-07-09 18:46
Oh sorry didn’t realise there was already an issue.
